/*
***********************************************************************************************************************************************************

												Levenberg-Marquardt Algorithm 
														Plotting Routine

Author: Omkar Junnarkar, Semester-3 MSc. Computational Material Science
Matriculation Nr.: 66157	Email: omkar.junnarkar@student.tu-freiberg.de
IDE : Microsoft Visual Studio 2019

Objective : Use the GNUPLOT-IOSTREAM Interface, and plot Measured and Fitted Curve

Libraries Included :

iostream: For Input-Output of the C++ Program
vector: To use vectors data type during file reading
src/rapidcsv: To read CSV files
gnuplot-iostream.h : Header-Only file to Link C++ iostream and GNUPLOT interface : Author Dan Stahlke [ Link in Main Program ]
plotme.h: Plotting Routine header file

*/

#include<iostream>
#include<vector>
#include"src/rapidcsv.h"
#include"gnuplot-iostream.h"
#include"plotme.h"

/*
	To reduce the effort of specifying libraries/class for each command/data type
*/

using namespace std;
using namespace rapidcsv;


/*
	Arguments: None
	Output: Plot (Measured Data, Fitted Data)

	The files generated by Fitting Routine are read by this function, wrote into 'vector', and then Plotted.
	[ See Documentation on github for Details(link in main.cpp) ]
*/

int plot() {

	/* 'gp' an instance of Gnuplot class, and 'dfit, dmeasured' are instances of Document class
		To use Gnuplot, as the argument of instance, it is required to give Path of executable file of Gnuplot.
	*/

	Gnuplot gp("\"C:\\Program Files\\gnuplot\\bin\\gnuplot.exe\"");
	Document dmeasured("y_measured.csv");
	Document dfit("final_fit.csv");
	
	vector<double> getmeasured = dmeasured.GetColumn<double>(0);
	vector<double> getfit = dfit.GetColumn<double>(0);
	
	/* Passing GNUPLOT commands through GNUPLOT syntax, in form of String to the instance 'gp' */

	gp << "set title 'FIT vs Measurement'\n";
	gp << "plot '-' with lines title 'Fit',"
		<< "'-' with lines title 'Measured'\n";
	gp.send(getfit);
	gp.send(getmeasured);

	cin.get();

};